filebeat.prospectors:

- input_type: log
  paths:
    - /Users/u099axm/dev/devops/data/*.txt

  fields:
    app: devops
    env: dev


filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml

setup.template.settings:
  index.number_of_shards: 3

output.logstash:
  hosts: ["localhost:5044"]

